### ISSUE TITLE
Can we change the language of this project to php ?

### ISSUE THREAD

**Issue by darklight147** [neeejm/sqli-echallenge-casa#5]
Currently, this project is using a different programming language: Java, and the request has been made to change it to PHP. As PHP is a popular language for web development, it would be a good idea to update the project to use this language.

**Comment by neeejm** [comment]
I will take the suggestion into consideration. I think what this project actually needs is a good ci/cd pipeline that would help us with getting feedback on the quality of the code and test the code before merging to main. If you don't mind volunteering? Can you provide us with one?

**Comment by darklight147** [comment]
Yes i would love to

**Comment by darklight147** [comment]
I can even make a CI/CD that when you merge into main it converts the branch from java to javascript ;)
